spring:
  datasource:
    #url: jdbc:h2:tcp://localhost/D:/Study/spring_jpa_basic/h2_db_home
    url:  jdbc:h2:tcp://localhost/D:/Dev/h2_db_home/spring_jpa_data
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
        #default_batch_fetch_size: 1000
        spring.jpa.properties.hibernate.use_sql_comments: true
logging.level:
  org.hibernate.SQL: debug
# org.hibernate.type: trace #띄어쓰기 2칸